name: Push Updates to Dependent Plugins
on:
  release:
    types:
      - released

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - id: remove-first-ver-char
        run: echo "::set-output name=VER::$(echo ${{ github.event.release.tag_name }} | cut -c 2-)"

      - name: Create repository dispatch event
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.MT_TOKEN }}
          repository: MaritimeMC/hub
          event-type: core-bump
          client-payload: '{"fragment": "minor", "core-version": "${{ steps.remove-first-ver-char.outputs.VER }}"}'