name: Push Updates to Dependent Plugins
on:
  release:
    types:
      - released

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Extract new core version name
        run: |
          version=$(echo ${{ github.event.release.tag_name }} | cut -c 2-)
          echo "VER=$version" >> $GITHUB_ENV

      - name: Set env for payload

      - name: Create repository dispatch event to Hub
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.MT_TOKEN }}
          repository: MaritimeMC/hub
          event-type: core-bump
          client-payload: '{"fragment": "bug", "core-version": "${{ env.VER }}"}'

      - name: Create repository dispatch event to BlockParty
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.MT_TOKEN }}
          repository: MaritimeMC/block-party
          event-type: core-bump
          client-payload: '{"fragment": "bug", "core-version": "${{ env.VER }}"}'